# Generated by Django 4.1.4 on 2023-05-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_saving',
            old_name='Emial',
            new_name='Email',
        ),
    ]
