# Generated by Django 4.1.4 on 2023-05-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_order_orderitem_product_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
