# Generated by Django 4.1.4 on 2023-05-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='qunatity',
        ),
    ]
