# Generated by Django 4.1.2 on 2023-05-25 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0014_order_product_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='customermodel',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='customermodel',
            old_name='username',
            new_name='Username',
        ),
    ]
