# Generated by Django 4.1.2 on 2023-05-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_rename_email_customermodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='Products',
            field=models.ManyToManyField(related_name='Products', to='App1.product'),
        ),
    ]
