# Generated by Django 4.1.2 on 2023-05-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0018_cartitem_delete_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
