# Generated by Django 4.1.4 on 2023-05-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0019_remove_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
    ]
